# config/packages/mypackage.yaml

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    MyPackage\MyService:
        arguments:
            $config: '%mypackage.config%'
