# src/StormailerBundle/Resources/config/services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        
    Sergiorutalita\Stm\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
    
    StormailerTransportFactory:
        arguments:
            $host: '%stormailer.host%'
            $port: '%stormailer.port%'
        tags:
            - { name: 'mailer.transport_factory' }
