# src/StormailerBundle/Resources/config/services.yaml
services:
    App\StormailerBundle\Mailer\Transport\StormailerTransportFactory:
        arguments:
            $host: '%stormailer.host%'
            $port: '%stormailer.port%'
        tags:
            - { name: 'mailer.transport_factory' }

